apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 8080
        hostPort: 8080
        listenAddress: "127.0.0.1"
        protocol: TCP

